# Generated by Django 6.0.1 on 2026-01-11 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_config', models.JSONField(blank=True, default=dict, null=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product')),
            ],
            options={
                'db_table': 'inventory',
                'unique_together': {('product', 'attribute_config')},
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.IntegerField(help_text='Positive for additions, negative for reductions')),
                ('action_type', models.CharField(choices=[('SALE', 'Sale'), ('RETURN', 'Return'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('INITIAL_STOCK', 'Initial Stock'), ('RESTOCK', 'Restock')], max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='inventory.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='products.product')),
            ],
            options={
                'db_table': 'inventory_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='inventory_a_timesta_032019_idx'), models.Index(fields=['product'], name='inventory_a_product_ca4a69_idx')],
            },
        ),
    ]
