# Generated by Django 6.0.1 on 2026-01-10 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(limit_choices_to={'is_seller': True}, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['store_slug'], name='stores_store_s_9cc63e_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['category'], name='stores_categor_34d041_idx'),
        ),
    ]
